name: Preview Deployment

on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: read
  deployments: write
  pull-requests: write

jobs:
  vercel-preview:
    name: Build and deploy preview
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Lint project
        run: yarn lint

      - name: Build project
        run: yarn build

      - name: Deploy preview to Vercel
        id: vercel-deploy
        uses: vercel/actions/deploy@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          working-directory: .

      - name: Share preview URL
        if: steps.vercel-deploy.outputs.preview-url
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          header: ":rocket: Preview"
          message: |
            🚀 A fresh preview deployment is ready!

            **Preview URL:** ${{ steps.vercel-deploy.outputs.preview-url }}
            **Inspect:** ${{ steps.vercel-deploy.outputs.inspect-url }}
